create table tb_worker (id int8 generated by default as identity, date_creation timestamp, date_update timestamp, status boolean not null, daily_income numeric(19, 2), name varchar(255), primary key (id));
INSERT INTO TB_WORKER (date_creation, status, name, daily_Income) VALUES (PARSEDATETIME('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'), true, 'Bob', 200.0);
INSERT INTO TB_WORKER (date_creation, status, name, daily_Income) VALUES (PARSEDATETIME('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'), true, 300.0);
INSERT INTO TB_WORKER (date_creation, status, name, daily_Income) VALUES (PARSEDATETIME('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'), true,'Alex', 250.0);
